### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [AmrDeveloper/LinkHub#1]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it still be ok for you to include your app in the F-Droid official repo?

**Comment by AmrDeveloper** [comment]
Hello @Poussinou

I know F-Droid and it's very good for me to add it to the official repo

Thanks

**Comment by ShareASmile** [comment]
any update on this? Open source community would love to see this very good app on fdroid soon!

**Comment by AmrDeveloper** [comment]
Hello @ShareASmile, 

Thanks for your interest in Linkhub, I will publish it on fdroid soon

**Comment by shuvashish76** [comment]
A "Requests For Packaging" has been opened here: https://gitlab.com/fdroid/rfp/-/issues/2101

@AmrDeveloper please double check if all the information I mentioned are correct.

**F-Droid Requirement:**

 * [ ] The upstream app source code repo contains the app metadata _(summary/description/images/changelog/etc)_ in a [Fastlane](https://gitlab.com/snippets/1895688) or [Triple-T](https://gitlab.com/snippets/1901490) folder structure

**Comment by IzzySoft** [comment]
@AmrDeveloper if you could attach an APK to the latest (and to future) release(s), I could immediately add your app to [my repo](https://apt.izzysoft.de/fdroid). During that process, I'd set up fastlane on my end anyway, which I could then provide you via a PR. Deal?

**Comment by AmrDeveloper** [comment]
@shuvashish76 Thank you i have checked all the info and they are correct and I will setup Fastlane during this or next week

**Comment by IzzySoft** [comment]
Thanks @AmrDeveloper! For the needs of my repo, just the APK suffices. But if it's no extra trouble, the AAB cannot hurt to be present as well – maybe someone else enjoys it. Maybe you could start with the latest release (1.1.1) already? Let me know when the APK is there and I'll pick it up.

**Comment by IzzySoft** [comment]
Thanks a lot! and [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) come the promised fastlane files. Your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.amrdeveloper.linkhub) with the next sync tomorrow around 6 pm UTC.

**Comment by AmrDeveloper** [comment]
@IzzySoft  Thank you so much for the PR

**Comment by FestplattenSchnitzel** [comment]
@AmrDeveloper Could you cover the Fastlane file structure changes under a new or existing [Git Tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging)?

**Comment by AmrDeveloper** [comment]
Hello @FestplattenSchnitzel,

Done I have added them to new tag 1.1.2

**Comment by licaon-kter** [comment]
Got the APK from the pipeline, signed it: https://gitlab.com/FestplattenSchnitzel/fdroiddata/-/jobs/2598907872/artifacts/file/tmp/com.amrdeveloper.linkhub_12.apk

Share to the app work :)

But long press on an entry makes the app crash :(
```
FATAL EXCEPTION: main
Process: com.amrdeveloper.linkhub, PID: 4257
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.text.DateFormat.format(DateFormat.java:306)
	at java.text.Format.format(Format.java:157)
	at com.amrdeveloper.linkhub.ui.link.LinkFragment.H(:21)
	at androidx.fragment.app.l.T(Unknown Source:19)
	at androidx.fragment.app.b0.f(:8)
	at androidx.fragment.app.b0.k(:8)
	at androidx.fragment.app.FragmentManager.C(:19)
	at androidx.fragment.app.FragmentManager.V(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.A(:4)
	at androidx.fragment.app.FragmentManager$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by AmrDeveloper** [comment]
Thanks, @licaon-kter for report,

I have solved it now, I will update the release and add apk and bundle
