### ISSUE TITLE
Export/Import as `.html` file

### ISSUE THREAD

**Issue by shuvashish76** [AmrDeveloper/LinkHub#12]
Would be nice if LinkHub could export/import links as `.html` file format.

Reason:
Most browsers export bookmarks as `.html` format. As bookmarks are nothing but links, folders with titles users could simply import them to LinkHub without adding them manually.

**Comment by Carpri1555** [comment]
> Would be nice if LinkHub could export/import links as `.html` file format.
> 
> Reason:
> Most browsers export bookmarks as `.html` format. As bookmarks are nothing but links, folders with titles users could simply import them to LinkHub without adding them manually.

https://console.jumpcloud.com/login/admin

**Comment by AmrDeveloper** [comment]
> Hello @AmrDeveloper, is this issue still actual? I could implement it on a different branch and offer a pull request with this feature

Sure feel free to implement it and make sure it not crash if user edited the html in wrong way

**Comment by AmrDeveloper** [comment]
Implemented in `1.6.0`
