### ISSUE TITLE
v1.1.2 F-Droid can't be updated by v1.1.3 F-Droid

### ISSUE THREAD

**Issue by uli-on** [AmrDeveloper/LinkHub#15]
**Describe the bug**
 Message displayed: 

"Incompatible version.
This version is signed with a different certificate than the one installed on your device. Uninstall that first."

**Comment by AmrDeveloper** [comment]
Hello @uli-on

This is weird because if it signed with the same key it will not be published on google play store, I will try to find the reason

Thanks 
Amr Hesham

**Comment by uli-on** [comment]
Any news on this? Cause I still can't update to v1.1.4

**Comment by AmrDeveloper** [comment]
Hello @uli-on,

Sorry for delay, but still can't find the reason, I suggest to export your data and import them from newer version for now, until we find the problem

Thanks
Amr Hesham

**Comment by uli-on** [comment]
Sorry for not yet being at home in your app, usually I'd do what you proposed on my own, but my most used bookmark app is still a commercial one I'd like to get rid of. But, yes, I hope you'll find the reason one day.

BTW, can you point me to that one topic where you mentioned your desire to modernise the design of this app? I've dabbled around with some screenshots I'd gladly post.

**Comment by AmrDeveloper** [comment]
@uli-on I have created different issues for UI Suggestions and we can make conversations about them

Please check: https://github.com/AmrDeveloper/LinkHub/issues/17

**Comment by SIRSteiner** [comment]
Since we are at v1.1.6 and you can do an export and import, is it really necessary at this moment to solve this issue or can we close it?

**Comment by uli-on** [comment]
Sorry, somehow I missed reading that last comment. I'll close the topic now.
