### ISSUE TITLE
Folder naming with more than 10 characters (making the limit 30 or limitless)

### ISSUE THREAD

**Issue by Skillanswer** [AmrDeveloper/LinkHub#18]
**Is your feature request related to a problem? Please describe.**
I can't name my folders with more than 10 characters. SO I used to name them with abbreviations . 
But as my number of folders is increasing ,it's getting more and more complicated to name them accurately. I can't be more creative in Naming them.

**Describe the solution you'd like**
As the title suggests, I want the limit of characters to be removed or at least be 30. 

**Additional context**
I absolutely love linkhub (Small size,the design and everything 😍) . Please make my life easier as that is what this app does anyways.

**Comment by AmrDeveloper** [comment]
Hello @Skillanswer,

I am happy that you used and loved the app, I will add this feature to the next release, if you have any feature request feel free to write it

Thanks
Amr Hesham
