### ISSUE TITLE
Export theme preference too

### ISSUE THREAD

**Issue by mecuricat** [AmrDeveloper/LinkHub#19]
**Is your feature request related to a problem? Please describe.**
It would be nice if user's theme preference (light/dark) is also considered into export settings.

**Comment by AmrDeveloper** [comment]
Hello @mecuricat,

Thank you for your suggestion I will implement it in the next release

Thanks
Amr Hesham

**Comment by SIRSteiner** [comment]
I think you can close this issue because it is implemented.

https://github.com/AmrDeveloper/LinkHub/releases/tag/1.2.0
