### ISSUE TITLE
Remember the last used folder when adding new link

### ISSUE THREAD

**Issue by mecuricat** [AmrDeveloper/LinkHub#21]
**Is your feature request related to a problem? Please describe.**
I am saving several links to a folder continuously but I have to change the folder name from **None** every time I add a new link.

**Describe the solution you'd like**
It would be helpful if the app remembers the last used folder. Please add a toggle in settings if user wants to set the last used folder as default instead of **None**.

**Comment by GalievBulat** [comment]
Hello, @AmrDeveloper, I could implement this task, so If this feature is still needed- then please assign it to me

**Comment by AmrDeveloper** [comment]
> Hello, @AmrDeveloper, I could implement this task, so If this feature is still needed- then please assign it to me

Sure, feel free to implement it

**Comment by AmrDeveloper** [comment]
This feature is implemented and released, thanks to @GalievBulat
