### ISSUE TITLE
Swipe to scroll is not smooth

### ISSUE THREAD

**Issue by mecuricat** [AmrDeveloper/LinkHub#22]
**Describe the bug**
When you swipe to scroll, it jitters and stops scrolling midway. I have to swipe several times to reach  even the second page of links.

**To Reproduce**
1. Save 15-20 links so that it does not fit in a single window and extends below. This is necessary for swiping.
2. Reopen LinkHub and swipe up.
3. You will notice that it scrolled only 2-3 links below and stopped.
4. Swipe several times to reach the end of second page.

**Expected behavior**
Scrolling should be smooth

**Screenshots**

<img src="https://user-images.githubusercontent.com/112750975/217221733-6f1ce2e8-bfb1-466e-b5ce-07b06d588f21.mp4" height="300px"/>

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 12
 - Version 1.1.5 (F-Droid build)

**Comment by AmrDeveloper** [comment]
Hello @mecuricat,

Thank you for the report, I will work on it, BTW I noticed that you used a dark theme and I am thinking of improving it more and trying to make the UI Simpler, more material and modern so if you have any suggestions you can share them

Thanks
Amr Hesham

**Comment by mecuricat** [comment]
Thanks for fixing it so quickly. :)

> ...to make the UI Simpler, more material and modern so if you have any suggestions you can share them

I will try to think of UI choices that could be more appealing to users. LinkHub is already awesome enough.

Regarding themes, I am thinking Light, Dark, Black (AMOLED), Material You and Custom.

In custom theme, like Simple Contacts Pro (v6.21.2 or lower) or Vinyl Music Player, you can adopt a Primary color and a Background color for theming different components.

<img src="https://user-images.githubusercontent.com/112750975/217638160-1954dbd8-43c2-4271-9921-1b03cb60c895.jpg" height="300px"/>

**Comment by AmrDeveloper** [comment]
@mecuricat Thanks for your suggestion i will improve dark theme first then add support for multi custom themes and add system theme option

**Comment by SIRSteiner** [comment]
Should you close this issue because it is fixed?
Themes discussion at https://github.com/AmrDeveloper/LinkHub/issues/17 ?

**Comment by AmrDeveloper** [comment]
@SIRSteiner I am still trying to find if it happens on any device with custom UI so I can add a solution for example make link folder none again

**Comment by mecuricat** [comment]
I will transfer the theme request to Design suggestions and close this issue.
