### ISSUE TITLE
App crash while trying to edit link after import

### ISSUE THREAD

**Issue by mecuricat** [AmrDeveloper/LinkHub#23]
**Describe the bug**
After importing data and trying to edit a link, app keeps stopping and exits. I am able to reproduce it 100% of the time.

**To Reproduce**
1. Create a folder by the name **Linux**, let's say.
2. Save a link under this Linux folder.
3. Export your data.
4. Uninstall and reinstall the app.
5. Import your data. You notice that only the link is imported. The Linux folder is not imported. I have a feeling that associated folder names are not exported in the first place.
6. Long press the link to edit it.
7. App crashes and exits the window. Maybe it is because the link cannot find the Linux folder associated with it.

**Expected behavior**
The edit page for the link appears together with the associated folder name.

<img src="https://user-images.githubusercontent.com/112750975/217236832-503bd3b7-e607-4e31-b1b0-5855d7633d17.jpg" height="300px"/>

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 12
 - Version 1.1.5 (F-Droid build)

**Additional context**
Xiaomi is notorious for modifying Android in undocumented ways. Recently, they had replaced Android's default text selection toolbar with their own broken version. Not sure if this is relevant, just thought of letting you know in case that is causing the crash.

**Comment by AmrDeveloper** [comment]
Hello @mecuricat,

Thank you so much for the report, I did the same steps on Huawei and Emulator and it did not crash the weird situation is that your folder is not exported, I will try to test on different devices and also handle case if it can't find link folder so maybe it should return to none in this case

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
Thats great @mecuricat,

I will try also and for other bugs and suggestions they will be available with in two days in the next release

**Comment by SIRSteiner** [comment]
I also tried to reproduce this issue. But here it works as expected with the same version from f-droid. Folder was also imported.

Device: Xiaomi Mi 9T Pro
OS: MIUI/Android 11

**Comment by mecuricat** [comment]
@SIRSteiner Thanks for testing. It is probably due to Android 12 then.

@AmrDeveloper Sorry about the delay. I am able to reproduce the same with LinkHub v1.1.6 on Realme 9 5G (Android 12/realme UI 3.0).

**Screenshot before export has Linux folder:**

<img src="https://user-images.githubusercontent.com/112750975/219923435-fd7460de-0dbe-49c9-84f8-c6e636ab49bd.jpg" height="300px"/>

---
**Screenshot after import has no folder:**

<img src="https://user-images.githubusercontent.com/112750975/219923438-cbf43610-baa3-434a-aa63-4b5633b88af9.jpg" height="300px"/>

---
**Screen recording of the crash:**

<img src="https://user-images.githubusercontent.com/112750975/219923446-df06357c-83fa-44d4-b18e-4e71a7c803ec.mp4" height="100px"/>

**Comment by SIRSteiner** [comment]
Can you provide the exported file?

**Comment by mecuricat** [comment]
GitHub says it does not support json file type.

**Comment by SIRSteiner** [comment]
Maybe upload to cloud or try to rename json to txt?

**Comment by mecuricat** [comment]
Please see the edited comment.

**Comment by SIRSteiner** [comment]
With yours here I can reproduce the crash. The file seems to be corrupt. Please try my exported file after renaming to json.

[1676789845846.txt](https://github.com/AmrDeveloper/LinkHub/files/10776399/1676789845846.txt)

**Comment by AmrDeveloper** [comment]
This JSON look like it missing folder color and also the variable names are not generated by GSON so we see a, b, c, d I think we can fix this issue by using `serialize name`

**Comment by mecuricat** [comment]
> With yours here I can reproduce the crash. The file seems to be corrupt.

I don't know why.

> Please try my exported file after renaming to json.
> [1676789845846.txt](https://github.com/AmrDeveloper/LinkHub/files/10776399/1676789845846.txt)

Yes, it imports correctly.

**Comment by AmrDeveloper** [comment]
@mecuricat Version 1.2.0 is now live it will be helpful to update it and check if this problem is solved or not

**Comment by mecuricat** [comment]
It still crashes because folder is not imported.

Device: Redmi Note 10 Pro
Android: 12
LinkHub: v1.2.0

The exported file:
```
{"folders":[{"clickedCount":1,"id":1,"isPinned":false,"name":"Linux"}],"links":[{"clickedCount":2,"createdTime":1676789838378,"folderId":1,"id":1,"isPinned":false,"isUpdated":false,"lastUpdatedTime":-1,"subtitle":"","title":"Authenticator—Linux Apps on Flathub","url":"https://flathub.org/apps/details/com.belmoussaoui.Authenticator"}],"showClickCounter":false,"theme":1}
```

#### Crash recording:

https://user-images.githubusercontent.com/112750975/221382322-a229ad98-c235-4140-b721-670b9e79df39.mp4

**Comment by AmrDeveloper** [comment]
@mecuricat Thanks, I see that the folder color is not in JSON file I will try to solve it and create also a check for this case

**Comment by mecuricat** [comment]
I think this issue can be marked as solved. I can no longer reproduce the issue. Thanks for fixing it so quickly. :)
