### ISSUE TITLE
A toggle for saving links automatically.

### ISSUE THREAD

**Issue by mecuricat** [AmrDeveloper/LinkHub#24]
**Is your feature request related to a problem? Please describe.**
Most often I would prefer that the app saves links without having to click Save. Not sure if others will like it.

**Describe the solution you'd like**
So, a toggle in settings would be perfect. Disabled by default. If enabled, app should be able to save links without having to click Save.

**Comment by SIRSteiner** [comment]
I think auto save should be the default if go back and it is no extra button for saving nor setting for that behavior necessary.

**Comment by AmrDeveloper** [comment]
I have implemented this feature for links and folders, it will available on the next release :D

**Comment by AmrDeveloper** [comment]
Solved in Release 1.3.0
