### ISSUE TITLE
import or export an .html file

### ISSUE THREAD

**Issue by franco27** [AmrDeveloper/LinkHub#25]
Hello
from an internet browser, we can export our favorites or bookmarks in an HTML file.

I would like your application to be able to import these favorites or bookmarks.

being able to create an HTML file containing the bookmarks would be nice from your application.

Thank you

**Comment by AmrDeveloper** [comment]
Thank you for your suggestion, its a good idea but first, we need to check the exported file from many browsers to write a general exporter and maybe we can target specific browser to import bookmarks for it

**Comment by franco27** [comment]
from a computer, most internet browsers have the function to export in HTML and also to import.
On Android, it's different. But generally speaking, open-source internet browsers have this possibility.

**Comment by franco27** [comment]
Most applications similar to yours offer to import bookmarks from an HTML file

**Comment by AmrDeveloper** [comment]
Implemented in `1.6.0`
