### ISSUE TITLE
Widget shows links twice or more after adding new link(s)

### ISSUE THREAD

**Issue by SIRSteiner** [AmrDeveloper/LinkHub#26]
**Describe the bug**
Widget shows links twice or more after adding a new pinned link

**To Reproduce**
1. Add a pinned link
2. Add the widget
3. Add a second pinned link
4. The first link is visible twice at the widget

**Expected behavior**
First added link(s) should be only one time at the widget.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro
 - OS: MIUI/Android 11

**Comment by SIRSteiner** [comment]
You can also reproduce this behavior if you edit an existing link.

**Comment by AmrDeveloper** [comment]
Hello @SIRSteiner, 

Thank you for reporting, I will check it and it will be fixed in next release soon,

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
@SIRSteiner It solved not and will be on next release

Thanks for helping

**Comment by SIRSteiner** [comment]
I checked that and it works. Thank you!
