### ISSUE TITLE
Add Folder Name to List of Links

### ISSUE THREAD

**Issue by BobJull** [AmrDeveloper/LinkHub#41]
In the list of Links it would be helpful to show which folder they relate to. (leave blank if they are not included in a folder)

**Comment by AmrDeveloper** [comment]
Hello @BobJull,

Thanks for your suggestion it is helpful but the problem is it will make the UI more complex link has a title, description, counter, and icon, if we added a folder name and icon it would be too much, but if we can think of more straightforward design we can add it, for example, we can remove the static icon at the start of each link and add the folder icon but there are a cases when folder name is too big

If you have an idea for a simpler design please share it and we can implement it

Thanks,
Amr Hesham

**Comment by BobJull** [comment]
Hi Amr

Thanks for your reply. Yes I understand that it could get crowded if the Folder Name is included also. Maybe you could add the folder name in the pop-up window that has 'Open in Browser', etc. It would save having to long press to find out which folder the Link name was in. 

Rgds Bob 



Get BlueMail for Android

**Comment by AmrDeveloper** [comment]
> Hi Amr Thanks for your reply. Yes I understand that it could get crowded if the Folder Name is included also. Maybe you could add the folder name in the pop-up window that has 'Open in Browser', etc. It would save having to long press to find out which folder the Link name was in. Rgds Bob Get BlueMail for Android
> […](#)
> On 8 Apr 2023, 12:31 am, at 12:31 am, Amr Hesham ***@***.***> wrote: Hello @BobJull, Thanks for your suggestion it is helpful but the problem is it will make the UI more complex link has a title, description, counter, and icon, if we added a folder name and icon it would be too much, but if we can think of more straightforward design we can add it, for example, we can remove the static icon at the start of each link and add the folder icon but there are a cases when folder name is too big If you have an idea for a simpler design please share it and we can implement it Thanks, Amr Hesham -- Reply to this email directly or view it on GitHub: [#41 (comment)](https://github.com/AmrDeveloper/LinkHub/issues/41#issuecomment-1500248328) You are receiving this because you were mentioned. Message ID: ***@***.***>

This is cool idea, and will keep the UI Simple, I will add it to the TODO, 

Thanks
Amr Hesham

**Comment by BobJull** [comment]
Hi Amr

If you include the folder name in the popup window, could you go to the folder by pressing on the folder name. That would take the user directly to other links in the same folder. If it is difficult to do, then no problem. 

I like your app, nice and simple to use

Rgds Bob 



Get BlueMail for Android

**Comment by AmrDeveloper** [comment]
> Hi Amr If you include the folder name in the popup window, could you go to the folder by pressing on the folder name. That would take the user directly to other links in the same folder. If it is difficult to do, then no problem. I like your app, nice and simple to use Rgds Bob Get BlueMail for Android
> […](#)
> On 8 Apr 2023, 8:49 am, at 8:49 am, Amr Hesham ***@***.***> wrote: > Hi Amr Thanks for your reply. Yes I understand that it could get crowded if the Folder Name is included also. Maybe you could add the folder name in the pop-up window that has 'Open in Browser', etc. It would save having to long press to find out which folder the Link name was in. Rgds Bob Get BlueMail for Android > […](#) > On 8 Apr 2023, 12:31 am, at 12:31 am, Amr Hesham ***@***.***> wrote: Hello @BobJull, Thanks for your suggestion it is helpful but the problem is it will make the UI more complex link has a title, description, counter, and icon, if we added a folder name and icon it would be too much, but if we can think of more straightforward design we can add it, for example, we can remove the static icon at the start of each link and add the folder icon but there are a cases when folder name is too big If you have an idea for a simpler design please share it and we can implement it Thanks, Amr Hesham -- Reply to this email directly or view it on GitHub: [#41 (comment)]([#41 (comment)](https://github.com/AmrDeveloper/LinkHub/issues/41#issuecomment-1500248328)) You are receiving this because you were mentioned. Message ID: ***@***.***> This is cool idea, and will keep the UI Simple, I will add it to the TODO, Thanks Amr Hesham -- Reply to this email directly or view it on GitHub: [#41 (comment)](https://github.com/AmrDeveloper/LinkHub/issues/41#issuecomment-1500631798) You are receiving this because you were mentioned. Message ID: ***@***.***>

Hello @BobJull,

I have implemented it now and when you click on the folder name it will go to the list of links of this folder

![Folder info in click dialog](https://user-images.githubusercontent.com/23631699/230680118-616cd101-9335-4ba3-9d3e-6b6df364d659.PNG)

Thanks and Enjoy LinkHub,
Amr Hesham

**Comment by AmrDeveloper** [comment]
Solved in Release 1.3.0
