### ISSUE TITLE
Android |  Add ability to create new folder on adding links from other apps

### ISSUE THREAD

**Issue by TrevorStreet** [AmrDeveloper/LinkHub#43]
**Is your feature request related to a problem? Please describe.**

No problem.  Love the app.  See feature req below.

**Describe the solution you'd like**

Would like to be able to create a new folder for the link I am adding when adding via the 'Share...'  menu option on various other apps.  

Currently when I am on a site I'd like to save to LinkHub, I tap share, then select LinkHub from the numerous apps installed.  When LinkHub opens it lets me add a new link in an existing folder of my choosing.  That's great.

What I want is to be able to add to my list of folders as I add to my list of links in LinkHub.

As it stands I do the following...

⏳  Save the link with 'Folder' set to none and 'Pinned?' set to yes.

⏳  Open LinkHub proper.

⏳  Create the new folder named for a category in which I want to classify my links.

⏳  Go back a screen and find the link in question, and edit to assign it to the new folder. 

  Not ideal.   And depends upon me having the time and patience at that moment to even bother with it.

**Describe alternatives you've considered**

Alternatives for bookmarks are plentiful, but I like LinkHub.  If I am being short sighted and missing an obvious solution please feel free to call me out for wasting your time.   I do not consider myself a LinkHub expert, but that's part of why I like it.  It just works and doesn't try to make itself into more than I want it to be.

**Additional context**

Thanks for the great work already.  If my suggestion isn't adopted you will not lose me as a customer.

**Comment by AmrDeveloper** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> No problem. Love the app. See feature req below.
> 
> **Describe the solution you'd like**
> 
> Would like to be able to create a new folder for the link I am adding when adding via the 'Share...' menu option on various other apps.
> 
> Currently when I am on a site I'd like to save to LinkHub, I tap share, then select LinkHub from the numerous apps installed. When LinkHub opens it lets me add a new link in an existing folder of my choosing. That's great.
> 
> What I want is to be able to add to my list of folders as I add to my list of links in LinkHub.
> 
> As it stands I do the following...
> 
> ⏳ Save the link with 'Folder' set to none and 'Pinned?' set to yes.
> 
> ⏳ Open LinkHub proper.
> 
> ⏳ Create the new folder named for a category in which I want to classify my links.
> 
> ⏳ Go back a screen and find the link in question, and edit to assign it to the new folder.
> 
> Not ideal. And depends upon me having the time and patience at that moment to even bother with it.
> 
> **Describe alternatives you've considered**
> 
> Alternatives for bookmarks are plentiful, but I like LinkHub. If I am being short sighted and missing an obvious solution please feel free to call me out for wasting your time. I do not consider myself a LinkHub expert, but that's part of why I like it. It just works and doesn't try to make itself into more than I want it to be.
> 
> **Additional context**
> 
> Thanks for the great work already. If my suggestion isn't adopted you will not lose me as a customer.

Hello @TrevorStreet,

It's great to head that you loved LinkHub, and thanks for suggesting new feature that will make it more easy to use the app, I have implemented it today and will be in the next release. enjoy it :D

Thank you,
Amr Hesham

**Comment by AmrDeveloper** [comment]
Preview

https://github.com/AmrDeveloper/LinkHub/assets/23631699/d654f784-d321-4772-8e93-f4160522eefb

**Comment by TrevorStreet** [comment]
That is fantastic.  Never expected to get an actual response but it is very appreciated.  Thank you for all your hard work.  I use your app every day.
