### ISSUE TITLE
Dark text cursor colour in dark theme

### ISSUE THREAD

**Issue by uli-on** [AmrDeveloper/LinkHub#44]
**Describe the bug**
In the dark theme, the text cursor and its handles are black on charcoal.

**To Reproduce**
1. Tap the plus button/FAB
2. Coose link or folder, regardless
3. Tap one of the text fields: a black cursor appears in a dark gray field.
4. Type some characters
5. Place the cursor between two letters: the single handle/pin is black, too
6. Mark some letters: two black handles appear.

**Expected behavior**
A more contrasting colour like e.g. white for improved visibility and handling

**Smartphone**
- Android 10
- Fairphone 3
- Linkhub v1.5.0

**Comment by AmrDeveloper** [comment]
Hello and Thank you for the suggestion, I have changed the color to light blue in a light/dark theme to be clear

![cursor color](https://github.com/AmrDeveloper/LinkHub/assets/23631699/9747681f-992d-4ad9-aaf3-2f1b2d7a734d)

It will be available in the next release

Thank you,
Amr Hesham

**Comment by uli-on** [comment]
Thanks, Amr, that will make editing easier and more precise.
