### ISSUE TITLE
Empty folder field entries

### ISSUE THREAD

**Issue by uli-on** [AmrDeveloper/LinkHub#45]
**Describe the bug**
Altough a folder entry has been filled in for a Link entry, often that entry remains void when long tapped for editing or controlling.

**To Reproduce**
1. Tap any folder containing links
2. Hold any link entry (it's associated with that folder so should have a folder entry)
3. The folder field is not set. If not: 
4. Close entry and try again, results often differ, but mostly the first attempt presents an empty folder field.

Also try from the startpage, in case measurements for fixing would be different for this screen.

**Expected behavior**
The folder field should contain an entry, if that value has been set.

**Smartphone**
Fairphone 3
Android 10
LinkHub v1.5.0

**Comment by AmrDeveloper** [comment]
Hello @uli-on,

Thanks for reporting this issue, i solved it and will be in the next release

Thank you,
Amr Hesham

**Comment by uli-on** [comment]
Thanks, Amr, I'm looking forward to the next release!
