### ISSUE TITLE
[Feature request] Chinese translation

### ISSUE THREAD

**Issue by Nriver** [AmrDeveloper/LinkHub#48]
I'm working on it.

**Comment by AmrDeveloper** [comment]
Thank you @Nriver ❤️

**Comment by goddaneel** [comment]
@AmrDeveloper 

The latest version of the Chinese text seems to be incomplete, I'm not sure if this is just an issue for me.

![Screenshot_2026-05-21-21-10-18-93_a873b20a71d81e345a34c8cbccdcd18d.jpg](https://github.com/user-attachments/assets/35a0fc9e-ffd4-47f2-a4be-3def1f890a4d)

![Screenshot_2026-05-21-21-11-57-84_a873b20a71d81e345a34c8cbccdcd18d.jpg](https://github.com/user-attachments/assets/e3f1ec58-8033-428a-b304-0ff1c3835fdb)

**Comment by AmrDeveloper** [comment]
@goddaneel During the reimplementation phase, I disabled the translation on the screen that migrated. For now, there are two steps to do

- Migrate the remaining screens.
- Re-enable different languages again and organize a better way for introducing a new translation

**Comment by goddaneel** [comment]
@AmrDeveloper 
Got it. Thanks for your hard work. I hope the reimplementation goes smoothly.
