### ISSUE TITLE
Add timestamp to each link

### ISSUE THREAD

**Issue by momobobe** [AmrDeveloper/LinkHub#5]
Please add timestamp to each link, which helps to organize and recall when there are lot of links

**Comment by AmrDeveloper** [comment]
Hello @momobobe, 

Thanks for your suggestion, it will be available in the next version

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
Hello @momobobe, 

The feature is done and the new version will be release soon on stores

Thanks
Amr Hesham

**Comment by SIRSteiner** [comment]
I think you can close this issue.
