### ISSUE TITLE
[Feature Request] Allow the link subtitle to be blank

### ISSUE THREAD

**Issue by urmomsangus** [AmrDeveloper/LinkHub#6]
When trying to add a link, it requires a subtitle which might not always be needed.

It would nice to have the option to not use a subtitle.

Thanks

**Comment by AmrDeveloper** [comment]
Hello @urmomsangus,

Thank you for this feature request, I have implemented it now and it will be available in the next release.

Thanks
Amr Hesham

**Comment by urmomsangus** [comment]
My sincerest thanks, it works perfectly.
