### ISSUE TITLE
Since version 1.6.0, your application no longer opens after clicking on the icon

### ISSUE THREAD

**Issue by franco27** [AmrDeveloper/LinkHub#62]
Hello,
Since the update to version LinkHub 1.6.0, I can no longer open your application.

I don't see the window and your application closes immediately (Crash)

I see that your application is trying to open but closes immediately and I don't see any window or error message.

I haven't tried uninstalling and reinstalling because I have a lot of saved bookmarks and I would like to be able to recover them.

I hope you can help me.

Xiaomi Redmi 8
CPU
QC_Reference_Phone
Qualcomm Technologies, Inc SDM439 (AArch64
Processor rev 4 (aarch64))
ABİs: arm64-v8a; armeabi-v7a; armeabi

720 x 1520 px (360 x 760 dp | 269 x 270 dp), 60 FPS
320 dpi (X-HDPI), Density 2.0, Scale 2.0

WIFI
User-Agent: Dalvik/2.1.0 (Linux; U; Android 10; Redmi 8 MIUI/
V12.5.2.0.QCNEUXM)
Proxy: -/--

**Comment by AmrDeveloper** [comment]
Hello @franco27,

Sorry for this crash, you updated the app from Google Play or F Droid, don't worry about your old links there are many solutions for example i can provide you an APK with roll back but with newer version until i fix it

I will test and fix it

Thank you

**Comment by franco27** [comment]
Hello
No, on Google Play or F Droid it's version 1.5.1.
I downloaded it on Github.
I would like to be able to restore and retrieve my bookmarks. Thank

**Comment by AmrDeveloper** [comment]
Hello @franco27,

Please download the new APK and install it, and update me if anything is wrong with it

Thank you,

**Comment by franco27** [comment]
Yes, I no longer have this problem, you have solved it.
I can now open the application without it closing immediately.
Thank you very much.

**Comment by AmrDeveloper** [comment]
Thank you, Enjoy it :D
